### PR TITLE
Peter edits

### LINKED ISSUE #27: New problem: no instance available
From the Cloogle log: ``Overloading error [MatchStrings.icl,54,is_substring`]: "%" no instance available of type Bool``.

### LINKED ISSUE #28: New problem: list brackets around charlist expected
From the Cloogle log: `Parse error [MatchStrings.icl,8;23,Expression]: List brackets, [ and ], around charlist '' expected`

### PR DESCRIPTION
**Pull request by peterachten**
worked on the new issue list, added two new error messages

Closes #27; closes #28.

### CODE REVIEW

**Comment by camilstaps** [comment]
The entries for #17 ('multiply defined') and #22 ('could not create .exe') I don't see yet here, perhaps you forgot to add some files?

**Comment by peterachten** [comment]
Everything looks fine on my side...

**Comment by peterachten** [comment]
If I look at the branch peter-edits, then these files are present (both in the readme and in the folder compiler-errors)

**Comment by peterachten** [comment]
Did the ( ) in the title cause the problem?

**Pull request merged**
